require('nyarthan.bootstrap')

require('nyarthan.plugins')

require('nyarthan.impatient')
require('nyarthan.utils')
require('nyarthan.options')
require('nyarthan.keymaps')
require('nyarthan.colorscheme')
require('nyarthan.cmp')
require('nyarthan.lsp')
require('nyarthan.comment')
require('nyarthan.gitsigns')
require('nyarthan.nvim-tree')
require('nyarthan.bufferline')
require('nyarthan.toggleterm')
require('nyarthan.lualine')
require('nyarthan.treesitter')
require('nyarthan.trouble')
require('nyarthan.git-worktree')
require('nyarthan.dressing')
require('nyarthan.telescope')
require('nyarthan.notify')
require('nyarthan.autopairs')
