require("nyarthan.bootstrap")

require("nyarthan.impatient")
require("nyarthan.utils")
require("nyarthan.options")
require("nyarthan.keymaps")
require("nyarthan.colorscheme")
require("nyarthan.cmp")
require("nyarthan.lsp")
require("nyarthan.autopairs")
require("nyarthan.comment")
require("nyarthan.gitsigns")
require("nyarthan.nvim-tree")
require("nyarthan.bufferline")
require("nyarthan.toggleterm")
require("nyarthan.lualine")
require("nyarthan.rust-tools")
require("nyarthan.treesitter")
require("nyarthan.trouble")
require("nyarthan.git-worktree")
require("nyarthan.dressing")
require("nyarthan.telescope-code-actions")
require("nyarthan.notify")
-- require("lsp-notify").setup()
